version: '3.2'
services:
  postgres:
    image: postgres:10
    container_name: postgres
    hostname: postgres
#    environment:
#      - POSTGRES_PASSWOD=postgres
#      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${CURRENT_HOST}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "notification-topic:1:1,output-topic:1:1"
    depends_on:
      - zookeeper