spring:
    profiles:
        active: dev
    jackson:
        property-naming-strategy: SNAKE_CASE
        serialization.write_dates_as_timestamps: false

logging:
    level:
        com.github.boilerplate: INFO


